services:
  app:
    container_name: cn-fleetfuel-app
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./.:/app
    # working_dir: /app
    ports:
      - '8188:4321'
    environment:
      HOST: '0.0.0.0'
      PORT: '4321'
      DB_HOST: db
      DB_PORT: '3306'
      DB_USER: usr_fleetfuel
      DB_PASSWORD: pwd_fleetfuel
      DB_NAME: db_fleetfuel
    #depends_on:
    #  db:
    #    condition: service_healthy
    restart: unless-stopped

  db:
    container_name: cn-fleetfuel-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db_fleetfuel
      MYSQL_USER: usr_fleetfuel
      MYSQL_PASSWORD: pwd_fleetfuel
      MYSQL_ROOT_PASSWORD: pwd_fleetfuel
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    container_name: cn-fleetfuel-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: pwd_fleetfuel
      UPLOAD_LIMIT: 300M
    ports:
      - '82:80'
    depends_on:
      - db

volumes:
  db_data:
